package com.kgc.demo.mapper;

import com.kgc.demo.dto.Fanuser;
import com.kgc.demo.dto.FanuserExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface FanuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fanuser
     *
     * @mbg.generated
     */
    long countByExample(FanuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fanuser
     *
     * @mbg.generated
     */
    int deleteByExample(FanuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fanuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fanuser
     *
     * @mbg.generated
     */
    int insert(Fanuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fanuser
     *
     * @mbg.generated
     */
    int insertSelective(Fanuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fanuser
     *
     * @mbg.generated
     */
    List<Fanuser> selectByExample(FanuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fanuser
     *
     * @mbg.generated
     */
    Fanuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fanuser
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Fanuser record, @Param("example") FanuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fanuser
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Fanuser record, @Param("example") FanuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fanuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Fanuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fanuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fanuser record);
}